# version: 2021.12.19
# author: Martin Kraemer, mk.maddin@gmail.com
# description: YAML configuration file - holding predefined entities
#   see: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md

sensor:
  #  - source: <property / attribute / namespacelist>
  #    id: <name of the charger attribute or prop to read>
  #    name: <optional: name of the sensor within HA>
  #    uid: <optional: unique ID postfix - required if multiple entities with same <id> value exist>
  #    description: <optional: key within HA>
  #    icon: <optional: key within HA>
  #    enabled: <optional: if set to False entity is by default disabled>
  #    device_class: <optional: key within HA>
  #    state_class: <optional: key within HA>
  #    unit_of_measurement: <optional: key within HA>
  #    entity_category: <optional: key within HA>
  #    value_id: <required for charger properties of type namespace: define which namespace attribute should be used as state value>
  #    namespace_id: <required for namespacelist source objects: define which item from the list of namespaces should be used>
  #    attribute_ids: <optional for charger properties of type namespace: define which namespace attributes should be included into HA>
  #    enum: <optional dict to map states to enum values>
  #    firmware: <optional string ">=1.1" | "<=1.1" | "==1.1" | "<1.1" | ">1.1" to setup entity only if charger firmware matches>
  #    variant: <optional string "11 / 22" to setup entity only if charger variant matches 11kW version or 22kW version>
  #    connection: <optional string "cloud / local" to setup entity only if charger connection type matches>
  #    default_state: <optional value to use as default state for "None"/"Null" charger properties - the default is STATE_UNKNOWN. Use with caution>
  #    html_unescape: <optional boolean to unescape HTML characters in state value>

  - source: attribute
    id: AccessState
    description: "State of access for the charger - values are: 'open', 'locked', 'auto'"
    icon: "mdi:lock-question"

  - source: attribute
    id: carConnected
    name: "Car Connected"
    description: "State of the car plug - values are: 'no car', 'charging', 'ready','complete'"
    icon: "mdi:ev-plug-type2"

  - source: namespacelist
    id: cards_0
    name: "ID Chip 0"
    description: "charging ID chip/card 0 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 0
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_1
    name: "ID Chip 1"
    description: "charging ID chip/card 1 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 1
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_2
    name: "ID Chip 2"
    description: "charging ID chip/card 2 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 2
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_3
    name: "ID Chip 3"
    description: "charging ID chip/card 3 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 3
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_4
    name: "ID Chip 4"
    description: "charging ID chip/card 4 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 4
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_5
    name: "ID Chip 5"
    description: "charging ID chip/card 5 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 5
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_6
    name: "ID Chip 6"
    description: "charging ID chip/card 6 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 6
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_7
    name: "ID Chip 7"
    description: "charging ID chip/card 7 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 7
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_8
    name: "ID Chip 8"
    description: "charging ID chip/card 8 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 8
    attribute_ids:
      - name
      - cardId
  - source: namespacelist
    id: cards_9
    name: "ID Chip 9"
    description: "charging ID chip/card 9 energy usage"
    icon: "mdi:credit-card-chip"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    enabled: False
    value_id: energy
    namespace_id: 9
    attribute_ids:
      - name
      - cardId

  #  - source: attribute
  #    id: errorState
  #    name: ChargingState
  #    description: "Charging state of the car - values are: 'Unknown Error', 'Idle', 'Charging', 'Wait Car', 'Complete', 'Error'"
  #    icon: "mdi:state-machine"
  #    enabled: False

  - source: property
    id: car
    name: "Car State"
    enum:
      0: "Unknown"
      1: "Idle"
      2: "Charging"
      3: "Wait Car"
      4: "Complete"
      5: "Error"
    description: "Charging state of the car - values are: 'Unknown', 'Idle', 'Charging', 'Wait Car', 'Complete', 'Error'"
    icon: "mdi:state-machine"

  - source: property
    id: cci
    name: "Inverter"
    description: "Connected solar inverter"
    icon: "mdi:solar-power"
    entity_category: diagnostic
    value_id: label
    html_unescape: True
    attribute_ids:
      - paired
      - model
      - commonName
      - ip
      - connected
      - status
      - message

  - source: property
    id: ccw
    name: "WiFi Connection"
    description: "WiFi connection information"
    icon: "mdi:wifi"
    entity_category: diagnostic
    value_id: ssid
    attribute_ids:
      - ip
      - netmask
      - gw
      - channel
      - bssid

  - source: property
    id: cus
    name: "Cable Unlock"
    enum:
      0: "Unknown"
      1: "Unlocked"
      2: "Unlock Failed"
      3: "Locked"
      4: "Lock Failed"
      5: "Lock/Unlock Power Out"
    description: "Cable unlock status - values are: 'Unknown', 'Unlocked', 'Unlock Failed', 'Locked', 'Lock Failed', 'Lock/Unlock Power Out'"
    icon: "mdi:state-machine"
    entity_category: diagnostic

  - source: property
    id: err
    name: "Internal Error"
    enum:
      0: "None"
      1: "FI AC"
      2: "FI DC"
      3: "Phase"
      4: "Overvolt"
      5: "Overamp"
      6: "Diode"
      7: "PP Invalid"
      8: "Gnd Invalid"
      9: "Contactor Stuck"
      10: "Contactor Missing"
      11: "FI Unknown"
      12: "Unknown"
      13: "Overtemp"
      14: "No Comm"
      15: "Status Lock Stuck Open"
      16: "Status Lock Stuck Locked"
      20: "Reserved 20"
      21: "Reserved 21"
      22: "Reserved 22"
      23: "Reserved 23"
      24: "Reserved 24"
    description: "Internal error state - values are: 'None', 'FI AC', 'FI DC', 'Phase', 'Overvolt', 'Overamp', 'Diode', 'PP Invalid', 'Gnd Invalid', 'Contactor Stuck', 'Contactor Missing', 'FI Unknown', 'Unknown', 'Overtemp', 'No Comm', 'Status Lock Stuck Open', 'Status Lock Stuck Locked', 'Reserved 20', 'Reserved 21', 'Reserved 22', 'Reserved 23', 'Reserved 24'"
    icon: "mdi:alert-circle"
    entity_category: diagnostic

  - source: property
    id: eto
    name: "Totally Charged"
    description: "Totally charged power"
    icon: "mdi:meter-electric"
    device_class: energy
    state_class: total
    unit_of_measurement: "Wh"
    default_state: -1
    #entity_category: diagnostic

  - source: property
    id: ffb
    name: "Lock Feedback"
    enum:
      0: "Unknown"
      1: "Unlocked"
      2: "Unlock Failed"
      3: "Locked"
      4: "Lock Failed"
      5: "Lock/Unlock Power Out"
    description: "Actual lock feedback - values are: 'Unknown', 'Unlocked', 'Unlock Failed', 'Locked', 'Lock Failed', 'Lock/Unlock Power Out'"
    icon: "mdi:lock-reset"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: lck
    name: "Effective lock setting"
    enum:
      0: "Normal"
      1: "AutoUnlock"
      2: "AlwaysLock"
      3: "ForceUnlock"
    description: "Lock setting, as sent to Charge Ctrl - values are: 'Normal', 'AutoUnlock', 'AlwaysLock', 'ForceUnlock'"
    icon: "mdi:lock"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: loc
    name: "Local Time"
    description: "Local time on the charger"
    icon: "mdi:clock-outline"
    enabled: False
    device_class: timestamp
    entity_category: diagnostic
    connection: local

  - source: property
    id: modelStatus
    name: "Charging Reason"
    enum:
      0: "Not Charging - No Charge Control Data"
      1: "Not Charging - Overtemperature"
      2: "Not Charging - Access Control Wait"
      3: "Charging - Force State On"
      4: "Not Charging - Force State Off"
      5: "Not Charging - Scheduler"
      6: "Not Charging - Energy Limit"
      7: "Charging - aWattar Price Low"
      8: "Charging - Automatic Stop Test"
      9: "Charging - Automatic Stop Not Enough Time"
      10: "Charging - Automatic Stop"
      11: "Charging - Automatic Stop No Clock"
      12: "Charging - PV Surplus"
      13: "Charging - Fallback Go-e Default"
      14: "Charging - Fallback Go-e Scheduler"
      15: "Charging - Fallback Default"
      16: "Not Charging - Fallback Go-e aWattar"
      17: "Not Charging - Fallback aWattar"
      18: "Not Charging - Fallback Automatic Stop"
      19: "Charging - Car Compatibility Keep Alive"
      20: "Charging - Charge Pause Not Allowed"
      22: "Not Charging - Simulate Unplugging"
      23: "Not Charging - Phase Switch"
      24: "Not Charging - Min Pause Duration"
      26: "Not Charging - Error"
      27: "Not Charging - Load Management Doesn't Want"
      28: "Not Charging - OCPP Doesn't Want"
      29: "Not Charging - Reconnect Delay"
      30: "Not Charging - Adapter Blocking"
      31: "Not Charging - Underfrequency Control"
      32: "Not Charging - Unbalanced Load"
      33: "Charging - Discharging PV Battery"
      34: "Not Charging - Grid Monitoring"
      35: "Not Charging - OCPP Fallback"
    description: "Reason why we allow charging or not right now - values are listed at: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md -> modelStatus"
    icon: "mdi:ev-station"
    entity_category: diagnostic

  - source: property
    id: nrg
    name: "Charging Power"
    description: "Charging power used for current car charging process"
    icon: "mdi:lightning-bolt-circle"
    device_class: power
    unit_of_measurement: W
    default_state: -1
    value_id: 11
    attribute_ids:
      - L1_Voltage:0
      - L2_Voltage:1
      - L3_Voltage:2
      - N_Voltage:3
      - L1_Ampere:4
      - L2_Ampere:5
      - L3_Ampere:6
      - L1_Power:7
      - L2_Power:8
      - L3_Power:9
      - N_Power:10
      - TotalPower:11
      - L1_PowerRelative:12
      - L2_PowerRelative:13
      - L3_PowerRelative:14
      - N_PowerRelative:15

  - source: property
    id: qsw
    name: "Webserver Queue"
    description: "Queue size webserver/websocket"
    icon: "mdi:web-sync"
    enabled: False
    entity_category: diagnostic
    firmware: "<=40.7"

  - source: property
    id: rbc
    name: "Reboot Counter"
    description: "Counts the number of boot operations."
    icon: "mdi:restart"
    enabled: False
    entity_category: diagnostic

  - source: property
    id: rbt
    name: "Reboot Timer"
    description: "Counts the milliseconds since the last boot. Expires after 49 days, increasing the reboot_counter."
    icon: "mdi:av-time"
    enabled: False
    device_class: duration
    unit_of_measurement: "ms"
    entity_category: diagnostic

  - source: property
    id: rssi
    name: "WiFi Signal"
    description: "Signal strength of the connected WiFi"
    icon: "mdi:wifi"
    enabled: False
    device_class: signal_strength
    default_state: 0
    unit_of_measurement: "dB"
    entity_category: diagnostic

  - source: property
    id: tma
    name: "Charger Temp"
    description: "Temperature of the controller"
    icon: "mdi:thermometer"
    device_class: temperature
    default_state: 999
    unit_of_measurement: "°C"
    entity_category: diagnostic

  - source: property
    id: trx
    name: "ID Chip Current"
    description: "Currently active transaction chip/card"
    icon: "mdi:credit-card-wireless"
    enabled: False
    default_state: 999
    enum:
      0: "No Chip"
      1: "ID Chip 0"
      2: "ID Chip 1"
      3: "ID Chip 2"
      4: "ID Chip 3"
      5: "ID Chip 4"
      6: "ID Chip 5"
      7: "ID Chip 6"
      8: "ID Chip 7"
      9: "ID Chip 8"
      10: "ID Chip 9"
      999: "No Transaction"

  - source: property
    id: wcch
    name: "HTTP Clients"
    description: "Webserver connected clients as HTTP"
    icon: "mdi:web-box"
    enabled: False
    entity_category: diagnostic
    firmware: "<=40.7"

  - source: property
    id: wccw
    name: "WEBSOCKET Clients"
    description: "Webserver connected clients as WEBSOCKET"
    icon: "mdi:web-box"
    enabled: False
    entity_category: diagnostic
    firmware: "<=40.7"

  - source: property
    id: wh
    name: "Connection Charged"
    description: "Energy in Wh since car connected"
    icon: "mdi:ev-station"
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: "Wh"
    default_state: 0

  - source: property
    id: wst
    name: "WiFi State"
    enum:
      0: "Idle"
      1: "No SSID Available"
      2: "Scan Completed"
      3: "Connected"
      4: "Connect Failed"
      5: "Connection Lost"
      6: "Disconnected"
      8: "Connecting"
      9: "Disconnecting"
      10: "No Shield"
    description: "WiFi status - values are: 'Idle', 'No SSID Available', 'Scan Completed', 'Connected', 'Connect Failed', 'Connection Lost', 'Disconnected', 'Connecting', 'Disconnecting', 'No Shield'"
    icon: "mdi:wifi-settings"
    enabled: False
    entity_category: diagnostic
